### ISSUE TITLE
Can't send feedback

### ISSUE THREAD

**Issue by dieechtenilente** [dieechtenilente/alcoholtestapp#51]
```

04-02 14:32:40.145 31707-32251/de.klaushackner.alkomat3000 I/System.out: [socket][12:-1] exception
    close [socket][::/:::-1]
04-02 14:32:40.146 31707-32251/de.klaushackner.alkomat3000 W/System.err: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:341)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:616)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
        at com.android.okhttp.Connection.connectSocket(Connection.java:221)
        at com.android.okhttp.Connection.connect(Connection.java:197)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:392)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:356)
04-02 14:32:40.147 31707-32251/de.klaushackner.alkomat3000 W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:273)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:478)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:261)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
        at de.klaushackner.breathalyzer.FeedbackSender.doInBackground(FeedbackSender.java:37)
        at de.klaushackner.breathalyzer.FeedbackSender.doInBackground(FeedbackSender.java:15)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by dieechtenilente** [comment]
Seems like a [custom mailer](https://github.com/go-gomail/gomail/issues/16) is needed.

**Comment by okitec** [comment]
Okay, I can make the server use gomail instead. Looks easy enough.

(BTW, I've used gomail for one thingy already, lel)

**Comment by dieechtenilente** [comment]
Many thanks in advance for that 👍

**Comment by dieechtenilente** [comment]
couldn't send mail: 504 5.7.4 Unrecognized authentication type
IT'S BACK!
